[package]
name = "web-push"
description = "Web push notification client with support for http-ece encryption and VAPID authentication."
version = "0.6.1"
authors = ["Julius de Bruijn <julius+github@nauk.io>"]
license = "Apache-2.0"
homepage = "https://github.com/pimeys/rust-web-push"
repository = "https://github.com/pimeys/rust-web-push"
documentation = "https://docs.rs/web-push/"
readme = "README.md"
keywords = ["web-push", "http-ece", "vapid"]
categories = ["web-programming", "asynchronous"]
edition = "2018"

[badges]
travis-ci = { repository = "pimeys/rust-web-push" }

[dependencies]
futures = "0.3"
hyper = "0.13"
hyper-tls = "0.4"
tokio = "0.2"
http = "^0.2"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
erased-serde = "^0.3"
ring = "^0.14"
untrusted = "^0.6"
native-tls = "^0.2"
base64 = "^0.7"
openssl = "^0.10"
time = "^0.1"
lazy_static = "^1.4"
chrono = "^0.4"
log = "^0.4"

[dev-dependencies]
argparse = "0.2"
tokio = { version = "0.2", features = ["rt-threaded", "macros"] }
